Job "getData (trigger: interval[0:00:02], next run at: 2018-04-02 09:42:20 CST)" raised an exception
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\aqua\stock\stocking\src\tools\T10.py", line 144, in getData
    df = ts.get_realtime_quotes(codeSplitMaps[key])
  File "D:\Python35\lib\site-packages\tushare\stock\trading.py", line 375, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "D:\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required
Job "getData (trigger: interval[0:00:02], next run at: 2018-04-02 09:42:22 CST)" raised an exception
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\aqua\stock\stocking\src\tools\T10.py", line 144, in getData
    df = ts.get_realtime_quotes(codeSplitMaps[key])
  File "D:\Python35\lib\site-packages\tushare\stock\trading.py", line 375, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "D:\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required
Job "getData (trigger: interval[0:00:02], next run at: 2018-04-02 09:42:24 CST)" raised an exception
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\aqua\stock\stocking\src\tools\T10.py", line 144, in getData
    df = ts.get_realtime_quotes(codeSplitMaps[key])
  File "D:\Python35\lib\site-packages\tushare\stock\trading.py", line 375, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "D:\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required
Job "getData (trigger: interval[0:00:02], next run at: 2018-04-02 09:42:26 CST)" raised an exception
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\aqua\stock\stocking\src\tools\T10.py", line 144, in getData
    df = ts.get_realtime_quotes(codeSplitMaps[key])
  File "D:\Python35\lib\site-packages\tushare\stock\trading.py", line 375, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "D:\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required
Job "getData (trigger: interval[0:00:02], next run at: 2018-04-02 09:42:28 CST)" raised an exception
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\aqua\stock\stocking\src\tools\T10.py", line 144, in getData
    df = ts.get_realtime_quotes(codeSplitMaps[key])
  File "D:\Python35\lib\site-packages\tushare\stock\trading.py", line 375, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "D:\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required
Job "getData (trigger: interval[0:00:02], next run at: 2018-04-02 09:42:30 CST)" raised an exception
Traceback (most recent call last):
  File "D:\Python35\lib\site-packages\apscheduler\executors\base.py", line 125, in run_job
    retval = job.func(*job.args, **job.kwargs)
  File "D:\aqua\stock\stocking\src\tools\T10.py", line 144, in getData
    df = ts.get_realtime_quotes(codeSplitMaps[key])
  File "D:\Python35\lib\site-packages\tushare\stock\trading.py", line 375, in get_realtime_quotes
    text = urlopen(request,timeout=10).read()
  File "D:\Python35\lib\urllib\request.py", line 162, in urlopen
    return opener.open(url, data, timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 503, in error
    result = self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 686, in http_error_302
    return self.parent.open(new, timeout=req.timeout)
  File "D:\Python35\lib\urllib\request.py", line 471, in open
    response = meth(req, response)
  File "D:\Python35\lib\urllib\request.py", line 581, in http_response
    'http', request, response, code, msg, hdrs)
  File "D:\Python35\lib\urllib\request.py", line 509, in error
    return self._call_chain(*args)
  File "D:\Python35\lib\urllib\request.py", line 443, in _call_chain
    result = func(*args)
  File "D:\Python35\lib\urllib\request.py", line 589, in http_error_default
    raise HTTPError(req.full_url, code, msg, hdrs, fp)
urllib.error.HTTPError: HTTP Error 401: Authorization Required
